server:
  port: 8080

feign:
  hystrix:
    enabled: true

val.url: http://VAL:8090
#val.url: http://localhost:8090

blackList.count: 2

logging:
  level:
    com.qred.service.ValidationResource: FULL